export const THEME_TOGGLE = 'THEME_TOGGLE';
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const FETCH_NODESTATUS_BEGIN = 'FETCH_NODESTATUS_BEGIN';
export const FETCH_NODESTATUS_SUCCESS = 'FETCH_NODESTATUS_SUCCESS';
export const FETCH_NODESTATUS_FAIL = 'FETCH_NODESTATUS_FAIL';

export const FETCH_DISCORD_USER_BEGIN = 'FETCH_DISCORD_USER_BEGIN';
export const FETCH_DISCORD_USER_SUCCESS = 'FETCH_DISCORD_USER_SUCCESS';
export const FETCH_DISCORD_USER_FAIL = 'FETCH_DISCORD_USER_FAIL';
export const FETCH_DISCORD_USER_IDLE = 'FETCH_DISCORD_USER_IDLE';

export const REVOKE_DISCORD_TOKEN_BEGIN = 'REVOKE_DISCORD_TOKEN_BEGIN';
export const REVOKE_DISCORD_TOKEN_SUCCESS = 'REVOKE_DISCORD_TOKEN_SUCCESS';
export const REVOKE_DISCORD_TOKEN_FAIL = 'REVOKE_DISCORD_TOKEN_FAIL';

export const LOGIN_DISCORD_USER_BEGIN = 'LOGIN_DISCORD_USER_BEGIN';
export const LOGIN_DISCORD_USER_SUCCESS = 'LOGIN_DISCORD_USER_SUCCESS';
export const LOGIN_DISCORD_USER_FAIL = 'LOGIN_DISCORD_USER_FAIL';

export const FETCH_DISCORD_USER_BALANCE_BEGIN = 'FETCH_DISCORD_USER_BALANCE_BEGIN';
export const FETCH_DISCORD_USER_BALANCE_SUCCESS = 'FETCH_DISCORD_USER_BALANCE_SUCCESS';
export const FETCH_DISCORD_USER_BALANCE_FAIL = 'FETCH_DISCORD_USER_BALANCE_FAIL';
export const FETCH_DISCORD_USER_BALANCE_IDLE = 'FETCH_DISCORD_USER_BALANCE_IDLE';

export const FETCH_TELEGRAM_USER_BEGIN = 'FETCH_TELEGRAM_USER_BEGIN';
export const FETCH_TELEGRAM_USER_SUCCESS = 'FETCH_TELEGRAM_USER_SUCCESS';
export const FETCH_TELEGRAM_USER_FAIL = 'FETCH_TELEGRAM_USER_FAIL';

export const REVOKE_TELEGRAM_TOKEN_BEGIN = 'REVOKE_TELEGRAM_TOKEN_BEGIN';
export const REVOKE_TELEGRAM_TOKEN_SUCCESS = 'REVOKE_TELEGRAM_TOKEN_SUCCESS';
export const REVOKE_TELEGRAM_TOKEN_FAIL = 'REVOKE_TELEGRAM_TOKEN_FAIL';

export const LOGIN_TELEGRAM_USER_BEGIN = 'LOGIN_TELEGRAM_USER_BEGIN';
export const LOGIN_TELEGRAM_USER_SUCCESS = 'LOGIN_TELEGRAM_USER_SUCCESS';
export const LOGIN_TELEGRAM_USER_FAIL = 'LOGIN_TELEGRAM_USER_FAIL';

export const FETCH_TELEGRAM_USER_IDLE = 'FETCH_TELEGRAM_USER_IDLE';
export const FETCH_TELEGRAM_USER_BALANCE_IDLE = 'FETCH_TELEGRAM_USER_BALANCE_IDLE';

export const FETCH_TELEGRAM_USER_BALANCE_BEGIN = 'FETCH_TELEGRAM_USER_BALANCE_BEGIN';
export const FETCH_TELEGRAM_USER_BALANCE_SUCCESS = 'FETCH_TELEGRAM_USER_BALANCE_SUCCESS';
export const FETCH_TELEGRAM_USER_BALANCE_FAIL = 'FETCH_TELEGRAM_USER_BALANCE_FAIL';
