export const THEME_TOGGLE = 'THEME_TOGGLE';
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const FETCH_NODESTATUS_BEGIN = 'FETCH_NODESTATUS_BEGIN';
export const FETCH_NODESTATUS_SUCCESS = 'FETCH_NODESTATUS_SUCCESS';
export const FETCH_NODESTATUS_FAIL = 'FETCH_NODESTATUS_FAIL';

export const FETCH_DISCORD_USER_BEGIN = 'FETCH_DISCORD_USER_BEGIN';
export const FETCH_DISCORD_USER_SUCCESS = 'FETCH_DISCORD_USER_SUCCESS';
export const FETCH_DISCORD_USER_FAIL = 'FETCH_DISCORD_USER_FAIL';
export const FETCH_DISCORD_USER_IDLE = 'FETCH_DISCORD_USER_IDLE';

export const REVOKE_DISCORD_TOKEN_BEGIN = 'REVOKE_DISCORD_TOKEN_BEGIN';
export const REVOKE_DISCORD_TOKEN_SUCCESS = 'REVOKE_DISCORD_TOKEN_SUCCESS';
export const REVOKE_DISCORD_TOKEN_FAIL = 'REVOKE_DISCORD_TOKEN_FAIL';

export const LOGIN_DISCORD_USER_BEGIN = 'LOGIN_DISCORD_USER_BEGIN';
export const LOGIN_DISCORD_USER_SUCCESS = 'LOGIN_DISCORD_USER_SUCCESS';
export const LOGIN_DISCORD_USER_FAIL = 'LOGIN_DISCORD_USER_FAIL';

export const FETCH_DISCORD_USER_BALANCE_BEGIN = 'FETCH_DISCORD_USER_BALANCE_BEGIN';
export const FETCH_DISCORD_USER_BALANCE_SUCCESS = 'FETCH_DISCORD_USER_BALANCE_SUCCESS';
export const FETCH_DISCORD_USER_BALANCE_FAIL = 'FETCH_DISCORD_USER_BALANCE_FAIL';
export const FETCH_DISCORD_USER_BALANCE_IDLE = 'FETCH_DISCORD_USER_BALANCE_IDLE';

export const FETCH_TELEGRAM_USER_BEGIN = 'FETCH_TELEGRAM_USER_BEGIN';
export const FETCH_TELEGRAM_USER_SUCCESS = 'FETCH_TELEGRAM_USER_SUCCESS';
export const FETCH_TELEGRAM_USER_FAIL = 'FETCH_TELEGRAM_USER_FAIL';

export const REVOKE_TELEGRAM_TOKEN_BEGIN = 'REVOKE_TELEGRAM_TOKEN_BEGIN';
export const REVOKE_TELEGRAM_TOKEN_SUCCESS = 'REVOKE_TELEGRAM_TOKEN_SUCCESS';
export const REVOKE_TELEGRAM_TOKEN_FAIL = 'REVOKE_TELEGRAM_TOKEN_FAIL';

export const LOGIN_TELEGRAM_USER_BEGIN = 'LOGIN_TELEGRAM_USER_BEGIN';
export const LOGIN_TELEGRAM_USER_SUCCESS = 'LOGIN_TELEGRAM_USER_SUCCESS';
export const LOGIN_TELEGRAM_USER_FAIL = 'LOGIN_TELEGRAM_USER_FAIL';

export const FETCH_TELEGRAM_USER_IDLE = 'FETCH_TELEGRAM_USER_IDLE';
export const FETCH_TELEGRAM_USER_BALANCE_IDLE = 'FETCH_TELEGRAM_USER_BALANCE_IDLE';

export const FETCH_TELEGRAM_USER_BALANCE_BEGIN = 'FETCH_TELEGRAM_USER_BALANCE_BEGIN';
export const FETCH_TELEGRAM_USER_BALANCE_SUCCESS = 'FETCH_TELEGRAM_USER_BALANCE_SUCCESS';
export const FETCH_TELEGRAM_USER_BALANCE_FAIL = 'FETCH_TELEGRAM_USER_BALANCE_FAIL';

export const FETCH_BOT_INFO_BEGIN = 'FETCH_BOT_INFO_BEGIN';
export const FETCH_BOT_INFO_SUCCESS = 'FETCH_BOT_INFO_SUCCESS';
export const FETCH_BOT_INFO_FAIL = 'FETCH_BOT_INFO_FAIL';
export const FETCH_BOT_INFO_IDLE = 'FETCH_BOT_INFO_IDLE';

export const FETCH_COIN_INFO_BEGIN = 'FETCH_COIN_INFO_BEGIN';
export const FETCH_COIN_INFO_SUCCESS = 'FETCH_COIN_INFO_SUCCESS';
export const FETCH_COIN_INFO_FAIL = 'FETCH_COIN_INFO_FAIL';

export const FETCH_PRICECURRENCIES_BEGIN = 'FETCH_PRICECURRENCIES_BEGIN';
export const FETCH_PRICECURRENCIES_SUCCESS = 'FETCH_PRICECURRENCIES_SUCCESS';
export const FETCH_PRICECURRENCIES_FAIL = 'FETCH_PRICECURRENCIES_FAIL';

export const FETCH_HISTORY_BEGIN = 'FETCH_HISTORY_BEGIN';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_FAIL = 'FETCH_HISTORY_FAIL';

export const FETCH_CHANGELOG_BEGIN = 'FETCH_CHANGELOG_BEGIN';
export const FETCH_CHANGELOG_SUCCESS = 'FETCH_CHANGELOG_SUCCESS';
export const FETCH_CHANGELOG_FAIL = 'FETCH_CHANGELOG_FAIL';
